# Generated by Django 5.2.5 on 2025-08-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Especie', models.CharField(max_length=25)),
                ('Sexo', models.CharField(max_length=10)),
                ('Raza', models.CharField(max_length=25)),
                ('Color', models.CharField(max_length=20)),
                ('Peso', models.CharField(max_length=6)),
            ],
        ),
    ]
