# Generated by Django 5.2.5 on 2025-09-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='Edad',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='Info',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='Color',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='animal',
            name='Peso',
            field=models.CharField(max_length=10),
        ),
    ]
