# Generated by Django 5.2.5 on 2025-09-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_animal_edad_animal_info_alter_animal_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='imagen',
            field=models.ImageField(null=True, upload_to='animales'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='Info',
            field=models.CharField(max_length=300),
        ),
    ]
