# Generated by Django 5.2.5 on 2025-09-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_animal_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='Info',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
